// Copyright (c) Open Enclave SDK contributors.
// Licensed under the MIT License.

#include <openenclave/host.h>
#include <stdio.h>

// Include the untrusted helloworld header that is generated
// during the build. This file is generated by calling the
// sdk tool oeedger8r against the helloworld.edl file.
#include "guess_u.h"

// This is the function that the enclave will call back into to
// print a message.

int main(int argc, const char* argv[])
{
    oe_result_t result;
    int ret = 1;
    oe_enclave_t* enclave = NULL;

    uint32_t flags = OE_ENCLAVE_FLAG_DEBUG;
    uint8_t max_value;
    uint8_t guess;

    bool is_correct;
    bool continue_game = true;

    if (argc != 2)
    {
        fprintf(
            stderr, "Usage: %s enclave_image_path [ --simulate  ]\n", argv[0]);
        goto exit;
    }

    // Create the enclave
    result = oe_create_guess_enclave(
        argv[1], OE_ENCLAVE_TYPE_AUTO, flags, NULL, 0, &enclave);
    if (result != OE_OK)
    {
        fprintf(
            stderr,
            "oe_create_helloworld_enclave(): result=%u (%s)\n",
            result,
            oe_result_str(result));
        goto exit;
    }

    // Call into the enclave
    printf("Enter a max value for the guessing game (must be inferior to 255) : ");
    scanf("%hhu", &max_value);
    printf("max_value : %hhu\n", max_value);

    result = init_enclave(enclave, max_value);
    if (result != OE_OK)
    {
        fprintf(
            stderr,
            "calling into enclave_helloworld failed: result=%u (%s)\n",
            result,
            oe_result_str(result));
        goto exit;
    }

    while (continue_game){
        printf("Enter a guess value : ");
        scanf("%hhu", &guess);
        printf("You entered %hhu\n", guess);

        enclave_guess(enclave, guess, &is_correct);
        if (is_correct)
        {
            printf("You won !\n");
            continue_game = false;
        }
        else
        {
            printf("Wrong guess !\n");
        }
    }

    ret = 0;

exit:
    // Clean up the enclave if we created one
    if (enclave)
        oe_terminate_enclave(enclave);

    return ret;
}
