// Copyright (c) Open Enclave SDK contributors.
// Licensed under the MIT License.

// Include the trusted helloworld header that is generated
// during the build. This file is generated by calling the
// sdk tool oeedger8r against the helloworld.edl file.
#include "guess_t.h"
#include <stdio.h>
#include "guess.h"

static ecall_dispatcher dispatcher;

// This is the function that the host calls. It prints
// a message in the enclave before calling back out to
// the host to print a message from there too.
void init_enclave(uint8_t max_value)
{
    dispatcher.initialize(max_value);
}

void enclave_guess(uint8_t input, bool* output)
{
    *output = dispatcher.guess(input);
}